pub const PARASANGA_SIZE: i32 = 64;
pub const WORLD_WIDTH_REGIONS: i32 = 8;
pub const WORLD_HEIGHT_REGIONS: i32 = 8;
pub const PLANET_TILE_WIDTH: i32 = PARASANGA_SIZE * WORLD_WIDTH_REGIONS;
pub const PLANET_TILE_HEIGHT: i32 = PARASANGA_SIZE * WORLD_HEIGHT_REGIONS;
